__title__ = 'Flask-Pretty'
__version__ = '0.1.0'
__description__ = 'Flask extension to output prettified HTML pages'
__author__ = 'Romain Clement'
__author_email__ = 'r.clement88@gmail.com'
__url__ = 'https://github.com/rclement/flask-pretty'
__license__ = 'MIT'
